### ISSUE TITLE
ERROR: Service "drupalphp70db" mounts volumes from "mysql-drupal-php70", which is not the name of a service or container.

### ISSUE THREAD

**Issue by ElijahLynn** [andrewholgate/docker-drupal-php70#6]
Too much of a Docker noob to fix this right now but thought I would at least post an issue. I get this error while trying to follow the install steps.

```
$ sudo docker-compose build
ERROR: Service "drupalphp70db" mounts volumes from "mysql-drupal-php70", which is not the name of a service or container.
```

I know it says to customize the Yaml file but I don't know enough yet to know what to do.

Seems related to https://github.com/docker/compose/issues/1972

Any advice appreciated.

**Comment by andrewholgate** [comment]
This error is saying that it cannot find the MySQL container. Perhaps you skipped [this step in the instructions](https://github.com/andrewholgate/docker-drupal-php70#create-presistant-database-data-only-container).

If you're new to Docker, I recommend you start with my [PHP70 project example](https://github.com/andrewholgate/docker-drupal-php70-example) which inherits from this container. I think it is a better starting point.
